###
POST https://localhost:5001/funcionario/create
Content-Type: application/json

{
  "nome": "Giovana",
  "cpf": "12345678900",
  "SetorId": 1
}

### Listar
GET https://localhost:5001/funcionario/list

### Alterar
PUT https://localhost:5001/funcionario/update
Content-Type: application/json

{
  "id": 5,
  "nome": "Pablo Escobar da cruz",
  "cpf": "151515151",
  "setorId": 2
}

### Buscar funcionario ID
GET https://localhost:5001/funcionario/findbyid/6

### Delete funcionario ID
DELETE  https://localhost:5001/funcionario/deleteid/2

### Delete funcionario ID
DELETE  https://localhost:5001/funcionario/deletename/Vitor

###############PONTO
###Criar
GET  https://localhost:5001/registro/now/6

### Listar
GET https://localhost:5001/funcionario/list

### Listar
GET https://localhost:5001/registro/list

###busque por funcionario
GET  https://localhost:5001/registro/list/3

###busque por funcionario
GET  https://localhost:5001/registro/teste/6