###
POST https://localhost:5001/funcionario/create
Content-Type: application/json

{
  "nome": "Vitor",
  "cpf": "12345678900"
}

### Listar
GET https://localhost:5001/funcionario/list

### Buscar funcionario ID
GET https://localhost:5001/funcionario/findbyid/2

### Buscar funcionario ID
GET https://localhost:5001/funcionario/deleteid/1
